export const ConvocationTipes = {
  CONVOCATION_TYPE_PIVE: "1",
  CONVOCATION_TYPE_PIVDO: "2",
  CONVOCATION_TYPE_ESTUDIANTES_VAN: "3",
  CONVOCATION_TYPE_ESTUDIANTES_VIENEN: "4",
  CONVOCATION_TYPE_DOCENTES_VAN: "5",
  CONVOCATION_TYPE_DOCENTES_VIENEN: "6",

}
