export enum ENUMConvocationTypeAcronym{
  PIVE="PIVE",
  PIVDO="PIVDO",
  COEVAN = "COEVAN",
  COEVIENEN = "COEVIENEN",
  CODVAN = "CODVAN",
  CODVIENEN = "CODVIENEN"
}

export enum ENUMConvocationCoevanStatus{
  SIN_ENVIAR = 1,
  ENVIADO = 2,
  EN_REVISION = 3,
  ACEPTADO = 4,
  OBSERVADO = 5,
  GANADO = 6,
  EN_DOCUMENTACION = 7,
  EN_SEGUIMIENTO = 8,
  EN_SEGUIMIENTO_OBSERVADO = 9,
  FINALIZADO = 10,
  FINALIZADO_OBSERVADO = 11,
  ANULADO_POSTULANTE = 12,//el postulante decide anular su postulación
  ANULADO_ADMIN = 13,
  NO_GANADOR = 14
}
